import product_01 from "../../assets/images/discover_shopnow/product_01.png";
import product_02 from "../../assets/images/discover_shopnow/product_02.png";
import product_03 from "../../assets/images/discover_shopnow/product_03.png";
import product_04 from "../../assets/images/discover_shopnow/product_04.png";
import product_05 from "../../assets/images/discover_shopnow/product_05.png";
export const shopNow = [
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_01,
  },
  // Duplicate sample for carousel
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_02,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_03,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_04,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_05,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_01,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_03,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "2kg"],
    reviews: 120,
    rating: 5,
    image: product_05,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_02,
  },
  {
    title: "Organic Raw Honey",
    price: 12.49,
    oldPrice: 15.0,
    discount: "Save 15%",
    weightOptions: ["500g", "1kg"],
    reviews: 120,
    rating: 5,
    image: product_03,
  },
];
